defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

development:
  <<: *defaults
  database: caturday_api_development
  options:
    safe: true
    skip_version_check: true

test:
  <<: *defaults
  database: caturday_api_test
  w: 0

# set these environment variables on your prod server
production:
  database: caturday_api
  uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    safe: true
    skip_version_check: true
